---
title: git
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
source("_knitr_config.R")
```

*********************************************************************

## links

git home: 

* [glossary](https://git-scm.com/docs/gitglossary)  
* [reference](https://git-scm.com/docs)  
* [book](https://git-scm.com/book/en/v2)  

github:  

* [glossary](https://help.github.com/en/articles/github-glossary)  
* [cheat sheet](https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdf)    

atlassian:

* [glossary](https://www.atlassian.com/git/glossary/terminology)  
* [tutorials](https://www.atlassian.com/git/tutorials)   

misc:  

* [happygitwithr](https://happygitwithr.com/)  
* [git tower](https://www.git-tower.com/learn/git/ebook/en/command-line/)  
* [youtube github guides](https://www.youtube.com/githubguides)  

*********************************************************************

## faqs

### create repos
* [create a repo from a local directory](#git-remote)  
* [clone a repo from github](#git-clone)  

### undo commits
* [amend a commit that hasn't been pushed](#git-commit-amend)   
* [undo a commit that hasn't been pushed](#git-reset)   
* [undo the last pushed commit](#git-revert-last-pushed-commit)
<!-- * delete a commit - see [git rebase](#git-rebase) -->

### manage branches
* [create a branch](#git-branch-create)  
* [delete a branch](#git-branch-delete)  

*********************************************************************

## installation

```sh
brew install git
git --version
which git

# configure
git config --global user.name "myUserName"
git config --global user.email myName@email.com
```

*********************************************************************

## .gitignore

* https://git-scm.com/docs/gitignore  
* https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#_ignoring  
* https://github.com/github/gitignore  
  * https://github.com/github/gitignore/blob/master/Python.gitignore  
  * https://github.com/github/gitignore/blob/master/R.gitignore  

Rules:

* standard glob patterns are are applied recursively:  
  * `*` zero or more characters  
  * `a/**/z` nested directories (e.g. `a/z`, `a/b/z`, `a/b/c/z`, etc.)  
  * `?` a single character  
  * `[abc]` any character in the brackets  
  * `[0-9]` any character from 0 to 9  
* `/` at the start of a pattern avoids recursivity  
* `/` at the end of a pattern specifies a directory  
* `!` at the end of a pattern negates it  

```
# ignore all .a files
*.a

# but do track lib.a, even though you're ignoring .a files above
!lib.a

# only ignore the TODO file in the current directory, not subdir/TODO
/TODO

# ignore all files in any directory named build
build/

# ignore doc/notes.txt, but not doc/server/arch.txt
doc/*.txt

# ignore all .pdf files in the doc/ directory and any of its subdirectories
doc/**/*.pdf
```

*********************************************************************

## commands

*********************************************************************

### git branch {#git-branch}

#### create {#git-branch-create}

```sh
# list branches
git branch # local branches
git branch -r # remote branches
git branch -a # local and remote branches

# create a new branch that is based on your currently checked out (HEAD) branch
git branch branch-name

# create a new branch on a different existing branch
git branch branch-name base-branch

# create branch and checkout 
git checkout -b branch-name base-branch
# the above line is shorthand for
git branch branch-name base-branch
git checkout branch-name

# push new branch to remote and set the remote as upstream 
git push --set-upstream origin branch-name
git push -u origin branch-name # same as above but using shortcut -u option
```

#### delete {#git-branch-delete}

```sh
# delete your local branch
git branch -d branch-name
git branch -D branch-name # forces the delete

# delete the remote branch
git push origin --delete branch-name
```

*********************************************************************

### git clone {#git-clone}

```sh
cd parent-folder
git clone https://github.com/owner/repo-name.git

# clone into folder with different name
git clone https://github.com/owner/repo-name.git different-name
```

*********************************************************************

### git commit {#git-commit}

#### --amend {#git-commit-amend}

E.g. amend the most recent commit, provided you haven't pushed it:

```sh
# change the commit message
got commit --amend # opens an editor

# change the content of the commit
git add my-amended-file.txt
git commit --amend
```

*********************************************************************

### git config {#git-config}

Specify configuration settings.

* https://www.datacamp.com/community/tutorials/git-setup

```sh
# view all of your settings
git config --list

# view all of your settings and where they are coming from
git config --list --show-origin
```

#### git config pull {#git-config-pull}

Specify how to reconcile divergent branches when using `git pull`

```sh
git config --global pull.rebase false  # merge (the default strategy)
git config --global pull.rebase true   # rebase
git config --global pull.ff only       # fast-forward only
```

E.g. user name and email

```sh
# view user name and email
git config --global user.name
git config --global user.email

# set user name and email
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
```

*********************************************************************

### git rebase {#git-rebase}

* this is dangerous because it rewrites the commit history  
* golden rule: never rebase published commits  

*TODO*

*********************************************************************

### git remote {#git-remote}

Manage remotes.

E.g. create a remote repo from a local directory:

```sh
# go to github and make the remote repo, 
# then do the following from your local machine:

# initialise your local repo if you haven't already done so
git init

# make at least one commit in your local repo to create the master branch
touch README.md
echo "# how2-cli" > README.md
git add README.md
git commit -m "first commit"

# add a new remote 
git remote add origin https://github.com/dkidney/how2-cli.git

# see which remote repo(s) the local repo is connected to (should be 'origin')
git remote
git remote -v # for more info

# set the origin as the default remote repository
git push -u origin master

# remove the remote if you ever need to 
git remote rm origin
```

*********************************************************************

### git reset {#git-reset}

E.g. undo the last commit, provided it hasn't been pushed:

```sh
# preserve changes in undone revisions
git reset --soft HEAD~1

# DELETE changes in undone revisions
git reset --hard HEAD~1
```

*********************************************************************

### git revert {#git-revert}

#### undo the last pushed commit {#git-revert-last-pushed-commit}

This makes a new commit that reverses the changes in the previous pushed commit.

```sh
# get the commit hash (e.g. from Github)
git revert 1f3601e4550d98fc6944ee2c52b2d4b9f4db96f3
# editor will automatically open to modify the commit message (in vim type :wq to exit)

# push the new commit
git push
```

#### undo a range of pushed commits {#git-revert-range-pushed-commits}

```sh
# reverts the commits between and including the specified commits
git revert <oldest_commit_hash>..<latest_commit_hash>
```

*********************************************************************

## github

### github pages

https://pages.github.com/

* sign in to [Github](https://github.com/login) and navigate to your repo  
* go to **Settings**  
* scroll down to the **Github Pages** section  
* under **Source** select **master branch** (or whatever option you prefer)  
* choose a theme if you want one  
* your pages should now be available at http://dkidney.github.io/how2-cli  

E.g. add a link in the readme:

```sh
touch README.md
echo '' >> README.md
echo 'http://dkidney.github.io/how2-cli' >> README.md
git add README.md
git commit -m "added github pages link to readme"
git push
```

*********************************************************************

## glossary

* https://git-scm.com/docs/gitglossary  
* https://linuxacademy.com/blog/linux/git-terms-explained  

term | description
------------- | -------------
branch | *todo*
HEAD | refers to the most recent commit of the repo in which you are working
origin | the conventional name of the remote repo
remote repo | a repo that tracks your local project but which lives remotely (e.g. on github)
upstream | i.e. where you push your changes to - e.g. the master branch of the remote repo

